version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -LO "https://dl.k8s.io/release/v1.27.6/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo "kubectl installed successfully."
      - kubectl version --client

  pre_build:
    commands:
      - echo Updating kubeconfig for EKS cluster...
      - aws eks update-kubeconfig --region $AWS_REGION --name three-tier-cluster

  build:
    commands:
      - echo Deploying Kubernetes manifests...
      - kubectl apply -f frontend-deployment.yaml
      - kubectl apply -f backend-deployment.yaml

artifacts:
  files:
    - '**/*'
