version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.6/2023-10-26/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/
      - echo "kubectl installed successfully."
      - kubectl version --client

  pre_build:
    commands:
      - echo Updating kubeconfig for EKS cluster...
      - aws eks update-kubeconfig --region $AWS_REGION --name three-tier-cluster

  build:
    commands:
      - echo Deploying Kubernetes manifests...
      - kubectl apply -f frontend-deployment.yaml
      - kubectl apply -f backend-deployment.yaml

artifacts:
  files:
    - '**/*'
