apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: IMAGE_URI_FRONTEND
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: LoadBalancer
  selector:
    app: php
  ports:
    - port: 80       # External LoadBalancer port
      targetPort: 80 # Apache inside container
